services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql-login
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: cristian
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
